// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ1WVRrrm3ypLVNJYIOFnRsXAMNsWq1bg',
    appId: '1:506561138290:web:9f8a21394e6035cf3dbceb',
    messagingSenderId: '506561138290',
    projectId: 'ca-kanno-yuki-tech-2025',
    authDomain: 'ca-kanno-yuki-tech-2025.firebaseapp.com',
    storageBucket: 'ca-kanno-yuki-tech-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK4VAyiGktkM9pQgP1SsxvVEbiOdH-DAs',
    appId: '1:506561138290:android:1c2093ab13c3005e3dbceb',
    messagingSenderId: '506561138290',
    projectId: 'ca-kanno-yuki-tech-2025',
    storageBucket: 'ca-kanno-yuki-tech-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-TVD8txH-wwKYqIABFVhY0TQxXzyZSK4',
    appId: '1:506561138290:ios:9db58fb21f012ff73dbceb',
    messagingSenderId: '506561138290',
    projectId: 'ca-kanno-yuki-tech-2025',
    storageBucket: 'ca-kanno-yuki-tech-2025.firebasestorage.app',
    iosBundleId: 'com.example.intNippontechsystemsOnseiproDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-TVD8txH-wwKYqIABFVhY0TQxXzyZSK4',
    appId: '1:506561138290:ios:9db58fb21f012ff73dbceb',
    messagingSenderId: '506561138290',
    projectId: 'ca-kanno-yuki-tech-2025',
    storageBucket: 'ca-kanno-yuki-tech-2025.firebasestorage.app',
    iosBundleId: 'com.example.intNippontechsystemsOnseiproDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ1WVRrrm3ypLVNJYIOFnRsXAMNsWq1bg',
    appId: '1:506561138290:web:e1031d4057f482023dbceb',
    messagingSenderId: '506561138290',
    projectId: 'ca-kanno-yuki-tech-2025',
    authDomain: 'ca-kanno-yuki-tech-2025.firebaseapp.com',
    storageBucket: 'ca-kanno-yuki-tech-2025.firebasestorage.app',
  );
}
